### ISSUE TITLE
Fails for ap-south-1 region

### ISSUE THREAD

**Issue by tridib** [awslabs/aws-codedeploy-plugin#66]
I am using plugin version 1.12. region is ap-south-1 (Mumbai) which is added recently. Upgrading the project to aws java sdk > 1.11.36 should fix it.

java.lang.IllegalArgumentException: Cannot create enum from ap-south-1 value!
    at com.amazonaws.regions.Regions.fromName(Regions.java:73)
    at com.amazonaws.codedeploy.AWSClients.<init>(AWSClients.java:74)
    at com.amazonaws.codedeploy.AWSClients.fromIAMRole(AWSClients.java:82)
    at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:209)
    at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Deploy an application to AWS CodeDeploy' marked build as failure

**Comment by kartiksky** [comment]
Change region like us-east-1 and it will work perfectly.

**Comment by Jmcfar** [comment]
This is fixed in Version 1.18 of the plug-in.

**Comment by kuldeepiitg** [comment]
I am trying similar thing, but still can't find Mumbai(AP_SOUTH_1) in Regions enum.

My pom have following dependency:
```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-core</artifactId>
    <version>1.2.0</version>
</dependency>
```
